### PR TITLE
Some QoT fixes, 32 bit mode and 64 bit mode

### PR DESCRIPTION
**Pull request by BlankHtmlPage**
You better test by yourself before accepting.

### CODE REVIEW

**Comment by 1tbfree** [comment]
ok, i will test it

**Comment by 1tbfree** [comment]
64bit one fails to compile with some syntax error or smth but it said smth on line 36

**Comment by 1tbfree** [comment]
32bit works fine

**Comment by 1tbfree** [comment]
ig i should merge it BUT type that testboot64 is broken in readme

**Comment by BlankHtmlPage** [comment]
Delete from the commit ig

**Comment by BlankHtmlPage** [comment]
I'll reopen the rp

**Comment by 1tbfree** [comment]
i can

**Pull request closed without merging**
